sudo: required
dist: trusty

language: generic

matrix:
  include:
    - env: PYTHON_VER="" PYTHON_PIP="" PYTAVE=no  SYMPY_VER=1.0.rc1 OCT_PPA=yes DOCTEST=yes COLUMNS=80
    - env: PYTHON_VER="3" PYTHON_PIP="3" PYTAVE=no  SYMPY_VER=1.0.rc1 OCT_PPA=yes DOCTEST=yes COLUMNS=80

# need octave devel pkgs for doctest (has compiled code as of July 2015)
before_install:
  - if [ "x$OCT_PPA" = "xyes" ]; then
        sudo apt-add-repository -y ppa:octave/stable;
    fi
  - sudo apt-get update -y;
  - sudo apt-get install -y octave liboctave-dev;
  - sudo apt-get install -y python$PYTHON_VER python$PYTHON_PIP-pip python$PYTHON_VER-dev libffi-dev libssl-dev;
  - "pip$PYTHON_PIP install --user 'requests[security]'"
  - "pip$PYTHON_PIP install --user https://github.com/sympy/sympy/archive/master.zip"
  - "pip$PYTHON_PIP list"
  - "pip$PYTHON_PIP show -f sympy"
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave -W --no-gui --eval "pkg install -forge doctest";
    fi
  - if [ "x$PYTAVE" = "xyes" ]; then
        sudo apt-get install -qq -y libboost-python-dev python-numpy;
        hg clone https://bitbucket.org/genuinelucifer/pytave_main;
        mv pytave_main pytave;
        pushd pytave;
        hg checkout travis;
        pwd;
        autoreconf --install || exit 1;
        ./configure && make || exit 1;
        popd;
    fi


# all commands here must have exit code 0 for the build to be called "passing"
# debugging: octave -W --no-gui --eval "syms x; A = [x sin(x) x^3]; A; exit(0)"
script:
  - octave -W --no-gui --eval "ver; pwd; exit(0)"
  - stty cols 80 rows 40
  - tput cols; stty size
  - pushd src; make; popd
  - pushd inst
  - octave --path=/home/travis/build/cbm755/octsympy/pytave -W --no-gui --eval "r = octsympy_tests; exit(r)"
  - cat octsympy_tests.log
  - if [ "x$DOCTEST" = "xyes" ]; then
        octave --path=/home/travis/build/cbm755/octsympy/pytave -W --no-gui --eval "pkg load doctest; syms x; r = doctest('.'); exit(~r)";
    fi
  - popd

#after_script:
#  - echo ${TRAVIS_TEST_RESULT}
